### ISSUE TITLE
What does CPCH mean? 

### ISSUE THREAD

**Issue by upuil** [MeteoSwiss/c4dl-lightningdl#1]
Dear Leinonen,  Thank you for you kindly open source your code. I'm try to reproduce your figure in your paper, but currently occur one issue after runing the `training.py`. What does CPCH mean? It seem didn't appear in the your paper. 
https://github.com/MeteoSwiss/c4dl-lightningdl/blob/41454c2704eef5673d043eecdf96a124fb322af1/scripts/training.py#L328-L335

**Comment by jleinonen** [comment]
Hi @upuil, 

Thanks for noticing this. These concern some data that we didn't end up using in the end. The lines should be safe to delete. I'll update the repository so this shouldn't be a problem any more.

Edit: should be now resolved in 711b0cc.

**Comment by upuil** [comment]
@jleinonen  Thank you for your quick reply!
