### ISSUE TITLE
setup_batch_gen

### ISSUE THREAD

**Issue by vivi7017** [MeteoSwiss/c4dl-lightningdl#3]
Thank you very much for sharing! When I try to call setup_batch_gen in training.py, it doesn't work. There is a break at dask.compute :
`    raw = {`
        `var_name: dask.delayed(regions.load_patches)(fn)`
  `      for (var_name, fn) in files.items()`
`    }`
`    raw = dask.compute(raw, scheduler="processes")[0]`
The final result shows:
 `concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.`
How can I fix it?

**Comment by jleinonen** [comment]
Hi @vivi7017,

I haven't seen this kind of error, not sure what would cause it. It looks like one of the data loader processes crashed while loading.

Can you try to run it without Dask? This should work, though it can be slow. If you see any errors there, maybe that can help you solve it.
```python
raw = {
var_name: regions.load_patches(fn)
for (var_name, fn) in files.items()
}
#raw = dask.compute(raw, scheduler="processes")[0]
```

**Comment by vivi7017** [comment]
Thanks for your quick answer! My previous dataset reading problem may be due to some file corruption when I uploaded. I reuploaded it and it was fixed.

**Comment by vivi7017** [comment]
Thanks for your quick answer! My previous dataset reading problem may be due to some file corruption when I uploaded. I reuploaded it and it was fixed.
