### ISSUE TITLE
the keys of the raw data

### ISSUE THREAD

**Issue by songqqqqq** [MeteoSwiss/c4dl-lightningdl#4]
I want to express my gratitude for kindly open sourcing your code. I am currently studying your paper "Seamless lightning nowcasting with recurrent-convolutional deep learning" and I am trying to understand the details of your code. However, I have encountered a problem with the keys of the raw data, which are "dict_keys(['patches', 'patch_coords', 'patch_times', 'zero_patch_coords', 'zero_patch_times', 'zero_value'])". Could you please provide me with more information on what these keys represent?

**Comment by jleinonen** [comment]
Hi, thanks for your interest in the code. The training data is is stored in patches of 32x32 pixel size from which the training samples are built. The `patches` variable contains the actual data and the `patch_coords` and `patch_times` fields encode the time and coordinates of each patch.

We also optimize the storage space by saving the location of "empty" patches (for example, for the precipitation variables, those patches that have no precipitation) separately, hence the `zero_patch_coords` and `zero_patch_times` fields. These are filled with `zero_value` when the patches are built.

**Comment by songqqqqq** [comment]
Thank you for your quick reply. I have been working with some data on convection patches and I have a couple of questions that I was hoping you could help me with.
Firstly, I have been able to easily understand the patch_coords and patch_times, but I am unsure about the zero_patch_coords. Could you help me determine what coordinates are stored in the zero_patch_coords?  if all points are zero, which point should use as zero_patch_coords? I would greatly appreciate any insights or explanations you may have on this.
Additionally, I have randomly plotted the patches data and patch_coords and have found that some of the coordinates appear to be outside of the convection area. I am unsure why this is the case and was hoping you might be able to shed some light on this issue.
Thank you in advance for your help.

the red point is the patch_coords corrsponding to the patches data.
![1J}3U6H{A1M06@BT(%H26S7](https://user-images.githubusercontent.com/129770270/232686362-c57570d1-be90-45f8-91a2-b6bb813f3df3.png)
![}%AZP{_P%{)DZ7L%8_43I5A](https://user-images.githubusercontent.com/129770270/232686583-e4d52cef-d4f4-4f8e-9faa-1e78c06608c1.png)

**Comment by jleinonen** [comment]
Hi, the `patch_coords` variable does not refer to coordinates in the patch but rather the coordinates of the patch itself when the training sample is constructed. For example, if you have four patches that have the same `patch_times` and their `patch_coords` are `(8,8)`, `(8,9)`, `(9,8)`, `(9,9)` then you can combine those patches to make a bigger training sample.

Some of the patches are outside the convection area because we are building bigger training samples out of them.

**Comment by songqqqqq** [comment]
Thank you very much for your reply! May I ask how the scale attribute in raw data  has been processed such as raw ["RZC"] ["scale"]?

**Comment by jleinonen** [comment]
The scale attribute is based on how the data were originally stored. I have retained it to keep the files smaller as it allows storing them in 8-bit format.

**Comment by songqqqqq** [comment]
Thank you very much for your answer! It is very helpful to my understand.
